# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "carmenpuccio/windows-server-2012-r2-test"

  config.vm.provider :virtualbox do |v, override|
    override.vm.network :private_network, ip: "192.168.0.12"
  end

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.vm.synced_folder "../shared", "/vagrantshared"
  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

  # This shell provisioner installs chocolatey and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "../shared/shell/main.cmd"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "ap_win2012r2" # this becomes the name of the virtual box
    vb.gui = true # do not run in headless mode
    vb.customize ["modifyvm", :id, "--vrde", "on"] # enable remote desktop 
    vb.customize ["modifyvm", :id, "--vrdeauthtype", "external"] # enable remote desktop  

vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
    puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.working_directory = "/vagrant"
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file  = "site.pp"

    puppet.facter = {
      "domain" => "local",
      "kernel" => "windows",
      "operatingsystem" => "windows",
      "osfamily" => "windows",
    }
   end
 end
